spring.application.name=rentora

#  Load .env from project root (requires Spring Boot 2.4+)
spring.config.import=optional:file:.env[.properties]

#  Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.maximum-pool-size=5

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=TRACE
logging.level.org.springframework.web.filter.CorsFilter=TRACE
logging.level.org.springframework.security.web.access.intercept=TRACE

#  JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=${JWT_ISSUER}
security.jwt.access-ttl-seconds=${JWT_ACCESS_TTL}
security.jwt.refresh-ttl-seconds=${JWT_REFRESH_TTL}
security.jwt.refresh-token-cookie-name=${JWT_REFRESH_COOKIE_NAME}
security.jwt.cookie-secure=${JWT_COOKIE_SECURE}
security.jwt.cookie-http-only=${JWT_COOKIE_HTTP_ONLY}
security.jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE}

#  Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile,openid

#  CORS
spring.cors.app=${FRONTEND_URL}

#  Cloudinary
spring.cloudinary.cloudname=${CLOUDINARY_CLOUD_NAME}
spring.cloudinary.api-key=${CLOUDINARY_API_KEY}
spring.cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#  Gemini
gemini.api.key=${GEMINI_API_KEY}

#  eSewa
esewa.secret-key=${ESEWA_SECRET_KEY}
esewa.merchant-code=${ESEWA_MERCHANT_CODE}
esewa.form-url=${ESEWA_FORM_URL}
esewa.success-url=${ESEWA_SUCCESS_URL}
esewa.failure-url=${ESEWA_FAILURE_URL}

#  Forecast
forecast.api-url=${FORECAST_API_URL}

#  Super admin
security.superadmin.email=${SUPER_ADMIN_EMAIL}
security.superadmin.password=${SUPER_ADMIN_PASSWORD}
security.superadmin.name=${SUPER_ADMIN_NAME}